const freeze = (values) => Object.freeze(Object.fromEntries(values.map((value) => [value, value])));

const ACCOUNT = freeze(["GUEST", "LOGGED_IN"]);
const APPLICATION = freeze(["NONE", "DRAFT", "SUBMITTED", "COMPLETED", "CANCELLED", "EXPIRED", "CLOSED"]);
const CHECKOUT_HOLD = freeze(["REQUESTED", "HELD", "CONSUMED", "RELEASED", "EXPIRED"]);
const PAYMENT = freeze(["NOT_STARTED", "PENDING", "PROCESSING", "SUCCEEDED", "FAILED", "REFUND_PENDING", "PARTIALLY_REFUNDED", "REFUNDED"]);
const PARTICIPATION = freeze(["NONE", "ACTIVE", "CANCELLED"]);
const SLOT_ALLOCATION = freeze(["NONE", "WAITLISTED", "CONFIRMED"]);
const RUN_RESULT = freeze(["NOT_STARTED", "STARTED", "COMPLETED", "NO_SHOW", "RETIRED", "INVALIDATED"]);
const FULFILLMENT = freeze(["NOT_PREPARED", "PREPARING", "SHIPPED", "DELIVERED", "RETURN_REQUESTED", "RETURNED"]);
const REGISTRATION = freeze(["NOT_OPEN", "OPEN", "CLOSED", "SUSPENDED"]);
const CAPACITY = freeze(["AVAILABLE", "LIMITED", "FULL"]);
const EVENT_STAGE = freeze(["PREPARING", "CORE_CONFIRMED", "SPOTS_CONFIRMED", "RIDE_PREPARATION", "RIDE_CHECK", "COUNTDOWN", "LIVE", "SEASON_CLEAR"]);
const CLOSE_REASON = freeze(["REGISTRATION_CLOSED", "REGISTRATION_SUSPENDED", "CAPACITY_FULL", "EVENT_UNAVAILABLE", "USER_BLOCKED"]);
const APPLICATION_STEP = freeze(["STEP_1", "STEP_2", "STEP_3"]);
const SURFACE_MODE = freeze(["MODE_A", "MODE_B", "MODE_C"]);
const PAYMENT_OUTCOME = freeze(["SUCCESS", "FAIL", "PROCESSING", "PROCESSING_THEN_SUCCESS", "PROCESSING_THEN_FAIL"]);

module.exports = {
  ACCOUNT,
  APPLICATION,
  APPLICATION_STEP,
  CAPACITY,
  CHECKOUT_HOLD,
  CLOSE_REASON,
  EVENT_STAGE,
  FULFILLMENT,
  PARTICIPATION,
  PAYMENT,
  PAYMENT_OUTCOME,
  REGISTRATION,
  RUN_RESULT,
  SLOT_ALLOCATION,
  SURFACE_MODE
};
