import puppeteer from 'puppeteer-core';
const executablePath=process.env.BROWSER_PATH;if(!executablePath)throw new Error('BROWSER_PATH is required');
const browser=await puppeteer.launch({headless:false,executablePath,protocolTimeout:120000,args:['--no-sandbox','--disable-dev-shm-usage','--ignore-gpu-blocklist','--enable-webgl','--use-gl=angle','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{
 const page=await browser.newPage();await page.setViewport({width:1920,height:1080,deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(`PAGEERROR: ${e.message}`));page.on('console',m=>{if(m.type()==='error')errors.push(`CONSOLE: ${m.text()}`)});
 await page.goto('http://127.0.0.1:4174/?qa=1',{waitUntil:'networkidle0',timeout:60000});await page.waitForSelector('#frame.ready',{timeout:45000});await sleep(350);if(!(await page.$('#three-stage canvas')))throw new Error('Three.js canvas missing');if(!(await page.evaluate(()=>Boolean(window.__scene05Timeline))))throw new Error('Scene 05 B timeline unavailable');if(errors.length)throw new Error(errors.join('\n'));
 async function capture(time,name){await page.evaluate(t=>{window.__scene05Timeline.pause().seek(t,false);const r=window.__qaRafCallback;if(typeof r!=='function')throw new Error('QA render callback unavailable');r(performance.now());},time);await sleep(150);await page.screenshot({path:`final/scene05-b/dist/${name}.png`});}
 await capture(1.35,'b29_014_peninsula');await capture(5.2,'b29_052_east_starts');await capture(8.8,'b29_088_road_choices');await capture(11.2,'b29_112_chosen_branch');await capture(18.5,'b29_185_freedom_reveal');await capture(24.2,'b29_242_network_flight');await capture(29.8,'b29_298_finish');await capture(34.2,'b29_342_sunset');await capture(37.2,'b29_372_firework');await capture(39.4,'b29_394_finale');
 const state=await page.evaluate(()=>({ready:document.querySelector('#frame').classList.contains('ready'),duration:window.__scene05Timeline.duration(),paused:window.__scene05Timeline.paused()}));if(!state.ready||!state.paused)throw new Error('Deterministic QA state not reached');if(state.duration<39.7||state.duration>40.8)throw new Error(`Unexpected v2.9 duration: ${state.duration}`);console.log(JSON.stringify(state));
}finally{await browser.close();}
