(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SSKR_MEMORIAL_JOURNEY=Object.freeze(api);})(typeof globalThis!=='undefined'?globalThis:this,()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const km=m=>(m/1000).toLocaleString('ko-KR',{maximumFractionDigits:1});
  const duration=s=>Math.floor(s/3600) ? `${Math.floor(s/3600)}시간 ${Math.floor(s%3600/60)}분` : `${Math.floor(s/60)}분`;
  const time=value=>new Date(value).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false});
  function decode(str){let i=0,lat=0,lon=0,out=[];while(i<str.length){const read=()=>{let n=0,s=0,b;do{b=str.charCodeAt(i++)-63;n|=(b&31)<<s;s+=5;}while(b>=32);return n&1?~(n>>1):n>>1;};lat+=read();lon+=read();out.push([lon/1e6,lat/1e6]);}return out;}
  function preview(item){const points=item.previewCoordinates||[];if(points.length<2)return '';const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);const minX=Math.min(...xs),maxY=Math.max(...ys),w=Math.max(...xs)-minX,h=maxY-Math.min(...ys),scale=Math.min(154/(w||1),84/(h||1));const xy=points.map(p=>[(p[0]-minX)*scale+12,(maxY-p[1])*scale+10]);return `<svg class="memorial-route-thumb" viewBox="0 0 180 108" aria-label="주행 경로 미리보기"><polyline points="${xy.map(p=>p.map(n=>n.toFixed(1)).join(',')).join(' ')}"/><circle cx="${xy[0][0]}" cy="${xy[0][1]}" r="4"/><circle class="finish" cx="${xy.at(-1)[0]}" cy="${xy.at(-1)[1]}" r="4"/></svg>`;}
  function gpx(record,title){const segments=record.legs.map(leg=>`<trkseg>${decode(leg.shape).map(([lon,lat],i)=>`<trkpt lat="${lat}" lon="${lon}"><time>${new Date(Date.parse(leg.startedAt)+leg.elapsedSeconds[i]*1000).toISOString()}</time></trkpt>`).join('')}</trkseg>`).join('');return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="SSKR synthetic event fixture" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>${esc(title)}</name><desc>SYNTHETIC TEST DATA. Simulated timestamps on Valhalla/OpenStreetMap road geometry. Not recorded GPS. Road data is from query time, not May 2026. © OpenStreetMap contributors, ODbL-1.0.</desc></metadata><trk><name>${esc(title)}</name>${segments}</trk></gpx>`;}
  const mapInteraction=typeof module==='object'&&module.exports?require('../shared/map/interaction'):window.SSKR_MAP_INTERACTION;
  const {createWheelSession}=mapInteraction;
  function mount(host,item,places){
    const controller=new AbortController(),byId=new Map(places.map(p=>[p.id,p]));let viewer,record,disposed=false;
    host.innerHTML='<div class="memorial-route-loading" role="status">주행 기록을 불러오고 있습니다.</div>';
    function select(index,open=false){
      const leg=record.legs[index-1];viewer.highlight(leg?decode(leg.shape).map(([lon,lat])=>[lat,lon]):[]);
      host.querySelectorAll('.journey-log-entry').forEach(e=>{e.classList.toggle('is-selected',Number(e.dataset.visit)===index);e.querySelector('[data-return]')?.remove();});
      const entry=host.querySelector('[data-visit="'+index+'"]');
      if(open){const button=document.createElement('button');button.type='button';button.className='sskr-map-return journey-log-return';button.dataset.return='';button.textContent='← 지도로 돌아가기';entry.querySelector('div:nth-child(2)').prepend(button);entry.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});}
    }
    function render(){
      host.innerHTML=`<div class="journey-map-host"></div><section class="journey-log"><header><div><h3>스팟과 주행 기록</h3><p>방문 순서대로 연결된 ${record.legs.length}개 주행 구간</p></div><button type="button" class="memorial-button is-secondary" data-download>테스트 주행기록 GPX ↓</button></header><div class="journey-log-list">${record.visits.map((c,i)=>{const p=byId.get(c.locationId),leg=record.legs[i-1];return `<article class="journey-log-entry" data-visit="${i}"><div class="journey-log-index">${i===0?'출':i===record.visits.length-1?'도':String(i)}</div><div><div class="journey-log-title"><h4>${esc(p?.name||c.locationId)}</h4><span>${time(c.arrivedAt)}${c.durationSeconds?' – '+time(c.departedAt):''}</span></div><p class="journey-log-meta">${c.durationSeconds ? Math.round(c.durationSeconds/60)+'분 정차 · ' : ''}누적 ${km(c.cumulativeDistanceMeters)}km</p><p>${esc(c.note)}</p>${c.snapDistanceMeters>100?`<p class="journey-access-note">주행 기록은 장소 주변 도로 접근점까지 연결됩니다. 원본 장소 좌표와 약 ${c.snapDistanceMeters}m 차이가 있습니다.</p>`:''}${leg?`<details><summary>직전 구간 ${km(leg.distanceMeters)}km · ${duration(leg.durationSeconds)} · 도로 정보</summary><p>${esc(leg.roadNames.join(' → ')||'도로명 없는 연결 도로')}</p></details>`:''}</div></article>`;}).join('')}</div></section><details class="journey-data-source"><summary>테스트 데이터와 출처</summary><p>2026년 5월 행사가 치러졌다고 가정한 합성 기록입니다. ${record.sampleCount.toLocaleString('ko-KR')}개 도로 좌표와 구간별 모의 시각을 연결했으며, 실제 참가자가 측정한 GPS 기록이 아닙니다.</p><p>경로: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL</a> / <a href="https://valhalla.github.io/valhalla/api/route/api-reference/" target="_blank" rel="noreferrer">Valhalla 이륜차 경로</a>. 조회 시점 도로망을 사용했으며 2026년 5월 당시 도로·영업·출입 조건의 검증 자료가 아닙니다. 장소 좌표는 기존 SSKR 카탈로그의 근사 좌표입니다.</p></details>`;
      const visits=record.visits.map((c,i)=>{const p=byId.get(c.locationId),photo=window.SSKR_MEMORIAL_STORE.selectPhoto(c);return {id:String(i),locationId:c.locationId,lat:c.coordinate[1],lng:c.coordinate[0],kind:i===0?'start':i===record.visits.length-1?'finish':'spot',number:i===0?'출':i===record.visits.length-1?'도':i,name:p?.name||c.locationId,region:p?.region||'',image:photo?.url||p?.image,meta:time(c.arrivedAt)};});
      viewer=window.SSKR_MAP.mount(host.querySelector('.journey-map-host'),{items:visits,catalog:visits,inView:false,inViewControl:false,cluster:false,route:record.legs.map(l=>decode(l.shape).map(([lon,lat])=>[lat,lon])),onSelect:p=>select(Number(p.id)),onOpen:p=>select(Number(p.id),true),onDeselect:()=>{host.querySelectorAll('.journey-log-entry').forEach(e=>e.classList.remove('is-selected'));}});
    }
    host.addEventListener('click',e=>{if(e.target.closest('[data-return]'))viewer.returnToMap();if(e.target.closest('[data-download]')&&record){const url=URL.createObjectURL(new Blob([gpx(record,item.title)],{type:'application/gpx+xml'}));const a=document.createElement('a');a.href=url;a.download=item.publicSlug+'-synthetic.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}},{signal:controller.signal});
    async function load(){try{const response=await fetch(item.routeUrl,{signal:controller.signal});if(!response.ok)throw Error('HTTP '+response.status);record=await response.json();if(disposed)return;if(record.id!==item.runSessionId||!record.legs?.length||!record.visits?.length)throw Error('Invalid journey');render();}catch(error){if(disposed||error.name==='AbortError')return;console.error('Memorial journey load failed',error);viewer?.destroy();host.innerHTML='<div class="memorial-route-loading" role="status">주행 기록을 불러오지 못했습니다. <button class="memorial-button is-secondary" type="button" data-retry>다시 불러오기</button></div>';host.querySelector('[data-retry]').addEventListener('click',load,{once:true,signal:controller.signal});}}
    load();return()=>{disposed=true;controller.abort();viewer?.destroy();};
  }
  return {decode,preview,gpx,mount,km,duration,time,createWheelSession};
});
