(() => {
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const deadline=v=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}):'별도 안내';
  const input=(name,label,value='',extra='')=>`<label class="prep-field"><span>${label}</span><input name="${name}" value="${esc(value)}" ${extra} required></label>`;
  function mount(root,context,{onUpdate,notices=[]}) {
    const rows=window.SSKR_EVENT_RULES.preparation(context),p=context.participation,e=context.event;
    const section=(key,title,body)=>{const row=rows.find(r=>r.key===key);return `<section class="prep-card" id="${key}"><header><h2>${title}</h2><span>${row.complete?'확인 완료':'확인 필요'}</span></header><p class="prep-deadline">${row.deadline?'수정 기한 '+deadline(row.deadline):'내용이 변경되면 다시 확인해 주세요.'}</p><form data-preparation="${key}"><fieldset ${row.editable?'':'disabled'}>${body}<button class="manager-primary" type="submit">${key==='notice'?'안내 확인 완료':'저장'}</button></fieldset><p role="status" class="prep-status"></p></form>${!row.editable?'<p>현재 수정할 수 없습니다. 운영 공지를 확인해 주세요.</p>':''}</section>`;};
    root.innerHTML=`<div class="prep-page"><header class="page-head"><div><p>PREPARATION</p><h1>참가 준비</h1></div><span>${esc(e.publicTitle)} · ${esc(p.participantNumber)}</span></header><p>공식 출발지는 참가 정보로 확정합니다. 개인 루트는 여러 개 저장하거나 자유롭게 수정할 수 있으며, 루트 수정으로 공식 출발지가 바뀌지 않습니다.</p><div class="prep-grid">${section('bike','바이크 정보',input('maker','제조사',p.bikeInfo?.maker)+input('model','모델명',p.bikeInfo?.model)+input('className','배기량 / 클래스',p.bikeInfo?.className))}${section('start','공식 출발지',`<label class="prep-field"><span>출발지</span><select name="startLocationId" required><option value="">출발지를 선택해 주세요</option>${window.SSKR_SPOT_CATALOG.filter(place=>place.kind==='start'&&(!e.startLocationIds||e.startLocationIds.includes(place.id))).map(place=>`<option value="${esc(place.id)}" ${place.id===p.selectedStartLocationId?'selected':''}>${esc(window.SSKR_MAP.formatPlaceText(place.name))} · ${esc(window.SSKR_MAP.formatPlaceText(place.region))}</option>`).join('')}</select></label><p>일출 이후 이 장소에서 출발 체크인을 합니다. 도착지는 ${esc(e.finishLocationName)}입니다.</p>`)}${section('kit','키트 사전 배송',`<p>입력한 주소로 참가 키트를 사전 발송합니다. 현재 상태: ${esc(({NOT_PREPARED:'발송 준비 전',PREPARING:'발송 준비 중',SHIPPED:'발송 완료',DELIVERED:'배송 완료'})[p.fulfillmentState]||'확인 중')}</p>${input('name','수령인',p.kitRecipient?.name,'autocomplete="name"')}${input('phone','휴대전화',p.kitRecipient?.phone,'type="tel" autocomplete="tel"')}${input('postalCode','우편번호',p.kitRecipient?.postalCode,'inputmode="numeric" pattern="[0-9]{5}" autocomplete="postal-code"')}${input('address','주소',p.kitRecipient?.address,'autocomplete="street-address"')}<label class="prep-field"><span>상세 주소 (선택)</span><input name="detail" value="${esc(p.kitRecipient?.detail)}"></label>`)}${section('notice','운영 안내 확인',`<p>공식 출발 체크인 → 서로 다른 경유 스팟 ${e.minimumSpotCheckins}곳 이상 체크인 → 일몰 전 공식 도착 체크인이 완주 조건입니다. 계획한 루트의 장소 수는 실제 체크인을 대신하지 않습니다.</p><p>행사 일정: ${esc(e.eventDateDisplay)} · 운영 안내 ${esc(e.preparationNoticeVersion)}</p>${notices.filter(n=>!n.eventId||n.eventId===e.id).map(n=>`<div class="prep-notice"><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p></div>`).join('')}<a href="/app/notices" data-app-link>운영 공지 전체 보기</a>`)}</div><a class="manager-link" href="/app" data-app-link>매니저로 돌아가기 →</a></div>`;
    root.querySelectorAll('[data-preparation]').forEach(form=>form.addEventListener('submit',async event=>{
      event.preventDefault();const values=Object.fromEntries(new FormData(form)),key=form.dataset.preparation;
      const action={bike:'SAVE_BIKE_INFO',start:'SAVE_START_LOCATION',kit:'SAVE_KIT_RECIPIENT',notice:'ACKNOWLEDGE_PREPARATION'}[key];
      const payload=key==='bike'?{bike:values}:key==='start'?{startLocationId:values.startLocationId}:key==='kit'?{recipient:values}:{version:e.preparationNoticeVersion};
      const status=form.querySelector('[role="status"]'),button=form.querySelector('button');button.disabled=true;
      try {const next=await window.SSKR_PARTICIPATE_API.application(action,payload);onUpdate(next);mount(root,next,{onUpdate,notices});const saved=root.querySelector('#'+key+' .prep-status');saved.textContent='저장했습니다.';saved.scrollIntoView({block:'nearest'});}catch(error){status.textContent=error.message;button.disabled=false;}
    }));
  }
  function profile(root,context,onUpdate) {
    const p=context.account.profile||{};
    root.innerHTML=`<section class="prep-page"><header class="page-head"><div><p>ACCOUNT</p><h1>내 계정</h1></div></header><form class="prep-card" id="profile-form">${input('name','이름',p.name,'autocomplete="name"')}${input('email','이메일',p.email,'type="email" autocomplete="email"')}${input('phone','휴대전화',p.phone,'type="tel" autocomplete="tel"')}<p>계정 연락처를 변경해도 제출한 참가 신청이나 배송 주소는 자동으로 변경되지 않습니다.</p><button class="manager-primary" type="submit">계정 정보 저장</button><p role="status"></p></form><a href="/app" data-app-link>매니저로 돌아가기 →</a></section>`;
    const form=root.querySelector('form');form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{onUpdate(await window.SSKR_PARTICIPATE_API.mock('UPDATE_ACCOUNT_PROFILE',{profile:Object.fromEntries(new FormData(form))}));form.querySelector('[role="status"]').textContent='계정 정보를 저장했습니다.';}catch(error){form.querySelector('[role="status"]').textContent=error.message;}finally{button.disabled=false;}});
  }
  window.SSKR_PREPARATION={mount,profile};
})();
