(function(root){'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const copy=v=>JSON.parse(JSON.stringify(v));
  const km=v=>Number.isFinite(v)?`${(v/1000).toFixed(1)} km`:'계산 전';
  const time=v=>{if(!Number.isFinite(v))return '계산 전';const m=Math.round(v/60);return m>=60?`${Math.floor(m/60)}시간 ${m%60}분`:`${m}분`;};
  const roadMessage=error=>/[가-힣]/.test(error?.message||'')?error.message:'도로 정보를 불러오지 못했습니다. 연결 상태를 확인하고 다시 시도해 주세요.';
  const SESSION='sskr.route-editor';
  const categories={cafe:'라이딩 · 카페',food:'맛집 · 시장',nature:'자연 · 전망',culture:'역사 · 마을'};
  function mount(host,options){
    const domain=root.SSKR_ROUTE_PLAN,catalog=options.catalog,byId=new Map(catalog.map(p=>[p.id,p])),viewer=options.viewer;
    let storage,session;try{storage=root.localStorage;}catch{}try{session=root.sessionStorage;}catch{}
    const store=domain.createStore(storage,catalog),provider=root.SSKR_ROUTE_PROVIDER.create(),events=new AbortController();
    let account=options.getAccount?.()||{},plan=domain.createEmpty(catalog),active=false,tab='route',sheet='half',dirty=false,selected=null,anchorId=null,replaceId=null;
    let providerStarted=false,ready=false,routeBusy=false,routeError='',providerError='',result=null,variant=0,preview=null,filterItems=[],candidateLimit=12,disposed=false,routeRequest=0,routeAbort=null,dialog=null,disposeDialog=null,flashTimer,scrollRestore=null;
    const undo=[];
    function recover(){try{const value=JSON.parse(session?.getItem(SESSION)||'null');if(value&&(value.ownerId===null||value.ownerId===(account.linked?account.id:null))){plan=domain.normalize(value.plan,catalog);active=value.active===true;dirty=value.dirty===true;anchorId=value.anchorId||plan.stopIds.at(-1)||plan.startId;selected=byId.get(value.selectedId)||byId.get(anchorId)||null;scrollRestore=value.viewport;}}catch{}}
    recover();
    function snapshot(){const map=viewer.getMap?.(),center=map?.getCenter();return center?{lat:center.lat,lng:center.lng,zoom:map.getZoom(),scrollY:root.scrollY}:scrollRestore;}
    function persist(){try{session?.setItem(SESSION,JSON.stringify({plan,active,dirty,anchorId,selectedId:selected?.id||null,ownerId:account.linked?account.id:null,viewport:snapshot()}));}catch{/* Restricted session storage must not interrupt editing. */}}
    function notify(message,error=false){const el=host.querySelector('.rp-notice');if(!el)return;clearTimeout(flashTimer);el.textContent=message;el.classList.toggle('is-error',error);el.hidden=false;flashTimer=setTimeout(()=>{el.hidden=true;},6000);}
    function status(p=plan){return domain.status(p,catalog,ready?provider:null);}
    function distanceSummary(p=plan){const value=status(p);return `<strong>${km(value.distanceMeters)}</strong><span>${time(value.durationSeconds)}</span>`;}
    function mapPlan(p=plan,fit=false){if(!active)return;const ids=p.startId?domain.orderedIds(p):[];viewer.setRoute?.(preview?preview.result?.legs||[]:result?.legs||[],{selectedIds:ids,activeId:anchorId,places:ids.map(id=>byId.get(id)).filter(Boolean),fit});}
    function currentId(){return (selected?.kind==='finish'?null:selected?.id)||anchorId||plan.stopIds.at(-1)||plan.startId;}
    function recommendations(){if(!ready||!plan.startId||preview)return[];return domain.nextRecommendations(plan,currentId(),catalog,provider,{limit:3});}
    function syncMap(fit=false){if(!active)return;mapPlan(preview?.plan||plan,fit);viewer.setCandidates?.(recommendations().map(item=>byId.get(item.placeId)).filter(Boolean));}
    function setMode(value){active=value;options.onModeChange?.(value,plan.startId);host.hidden=!value;viewer.setEditing?.(value);if(value){render();syncMap();if(selected)viewer.select?.(selected.id);if(!providerStarted)loadProvider();}persist();}
    async function calculate(fit=false){
      const request=++routeRequest;routeAbort?.abort();routeError='';
      const ids=domain.orderedIds(plan),pairs=new Set(ids.slice(1).map((id,i)=>ids[i]+'\u0000'+id));
      // Keep unchanged roads visible while replacing only the edited connections.
      result=result?{legs:result.legs.filter(leg=>pairs.has(leg.fromId+'\u0000'+leg.toId))}:null;
      if(!ready||!plan.startId){result=null;routeBusy=false;render();syncMap();return;}
      routeBusy=true;routeAbort=new AbortController();render();syncMap();
      try{const next=await provider.route(domain.orderedIds(plan),{signal:routeAbort.signal});if(disposed||request!==routeRequest)return;result=next;routeError=next.valid?'':'도로를 연결할 수 없는 구간이 있습니다. 장소를 바꾸거나 순서를 조정해 주세요.';}
      catch(error){if(disposed||request!==routeRequest||error?.name==='AbortError')return;routeError=roadMessage(error);}
      finally{if(!disposed&&request===routeRequest){routeBusy=false;render();syncMap(fit);}}
    }
    function change(next,message,fit=false){undo.push(copy(plan));if(undo.length>30)undo.shift();plan=domain.normalize(next,catalog);dirty=true;preview=null;persist();calculate(fit);if(message)notify(message);}
    function start(id){if(!byId.has(id)||byId.get(id).kind!=='start')return;anchorId=id;selected=byId.get(id);change({...plan,startId:id},'출발지를 선택했습니다. 경유지를 직접 고르거나 10곳을 추천받으세요.');options.onStartChange?.(id);viewer.select?.(id);viewer.getMap?.()?.flyTo([selected.lat,selected.lng],Math.max(10,viewer.getMap().getMinZoom()),{animate:false});}
    function add(id){const place=byId.get(id);if(!place)return;if(place.kind==='start'){start(id);return;}if(place.kind!=='spot')return;
      if(!plan.startId){tab='route';render();notify('먼저 출발지를 선택해 주세요.');return;}
      if(plan.stopIds.includes(id)){anchorId=id;render();notify('이미 경유지에 담긴 스팟입니다.');return;}
      const stops=plan.stopIds.slice();if(replaceId){const index=stops.indexOf(replaceId);if(index>=0)stops[index]=id;else stops.push(id);replaceId=null;}else{const index=anchorId===plan.startId?-1:stops.indexOf(anchorId);stops.splice(index>=0?index+1:anchorId===plan.startId?0:stops.length,0,id);}
      anchorId=id;selected=place;tab='route';change({...plan,stopIds:stops},`${place.name}을 경유지에 담았습니다.`);viewer.select?.(id);
    }
    function select(place){if(!active||!place||(!plan.startId&&place.kind!=='start'))return;selected=byId.get(place.id)||place;if(plan.stopIds.includes(place.id)||plan.startId===place.id){anchorId=place.id;tab='route';}else if(place.kind==='finish')tab='route';else tab='places';candidateLimit=12;render();syncMap();persist();}
    function card(place,{recommendation=null}={}){if(!place)return'';const included=plan.stopIds.includes(place.id)||plan.startId===place.id;
      return `<article class="rp-place${selected?.id===place.id?' is-selected':''}" data-place-id="${esc(place.id)}"><button type="button" class="rp-place-view" data-rp-action="select" data-id="${esc(place.id)}" aria-label="${esc(place.name)} 장소 확인">${place.image?`<img src="${esc(place.image)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:'<span class="rp-photo-empty"></span>'}<span><small>${esc(place.region)}</small><strong>${esc(place.name)}</strong>${recommendation?`<em>이전 지점부터 ${km(recommendation.fromDistanceMeters)} · 전체 +${km(recommendation.addedDistanceMeters)}</em>`:`<em>${esc(place.kind==='start'?'출발지':place.kind==='finish'?'고정 도착지':categories[place.category]||'스팟')}</em>`}</span></button>${recommendation?`<p>${esc(recommendation.reason)}</p>`:''}<button type="button" class="rp-place-add" data-rp-action="add" data-id="${esc(place.id)}" ${included||place.kind==='finish'?'disabled':''}>${included?'선택됨':place.kind==='start'?'출발지 선택':place.kind==='finish'?'도착지 고정':replaceId?'이 장소로 교체':'+ 경유지 추가'}</button></article>`;
    }
    function pointRow(id,index,kind){const place=byId.get(id),name=place?.name||'더 이상 제공되지 않는 장소',isStop=kind==='spot';
      return `<li class="rp-waypoint${anchorId===id?' is-active':''}${!place?' is-missing':''}" data-waypoint="${esc(id)}"${isStop?' draggable="true"':''}><button type="button" class="rp-point-main" data-rp-action="anchor" data-id="${esc(id)}" aria-label="${esc(name)}${isStop?' 다음에 경유지 추가':''}"><span class="rp-point-number ${kind}">${isStop?index+1:kind==='start'?'출':'도'}</span><span><small>${kind==='start'?'출발지':kind==='finish'?'고정 도착지':esc(place?.region||'위치 확인 필요')}</small><strong>${esc(name)}</strong></span></button>${isStop?`<div class="rp-row-actions"><button type="button" data-rp-action="up" data-id="${esc(id)}" aria-label="${esc(name)} 위로 이동" ${index===0?'disabled':''}>↑</button><button type="button" data-rp-action="down" data-id="${esc(id)}" aria-label="${esc(name)} 아래로 이동" ${index===plan.stopIds.length-1?'disabled':''}>↓</button><button type="button" data-rp-action="replace" data-id="${esc(id)}" aria-label="${esc(name)} 교체">교체</button><button type="button" data-rp-action="remove" data-id="${esc(id)}" aria-label="${esc(name)} 삭제">×</button></div>`:''}</li>`;
    }
    function routeContent(){const stats=status(),rec=recommendations();return `<div class="rp-route-grid"><div class="rp-route-selected"><div class="rp-section-title"><h3>내 경로</h3><span>출발 → 경유 → 도착</span></div><div class="rp-start-field"><label for="rp-start">출발지</label><select id="rp-start"><option value="">동해안·부산에서 출발지 선택</option>${catalog.filter(p=>p.kind==='start').map(p=>`<option value="${esc(p.id)}" ${p.id===plan.startId?'selected':''}>${esc(p.name)} · ${esc(p.region)}</option>`).join('')}</select></div>
      <div class="rp-auto"><div><strong>${plan.stopIds.length>=10?'다른 하루를 그려보세요':'어디를 들를지 고민이라면'}</strong><p>${plan.stopIds.length>=10?'선택한 장소의 방문 순서를 정리할 수 있어요.':'직접 고른 스팟을 유지하며 경유 10곳을 채워드려요.'}</p></div><button type="button" class="rp-primary" data-rp-action="autofill" ${!plan.startId||!ready||plan.stopIds.length>=10?'disabled':''}>10곳 추천받기</button></div>
      <div class="rp-route-tools"><span>출발 → 경유 ${plan.stopIds.length}곳 → 도착</span><button type="button" data-rp-action="undo" ${undo.length?'':'disabled'}>실행 취소</button><button type="button" data-rp-action="optimize" ${plan.stopIds.length<2||!ready?'disabled':''}>순서 정리</button></div>
      <ol class="rp-waypoints">${plan.startId?pointRow(plan.startId,-1,'start'):'<li class="rp-start-empty">출발지를 선택하면 경로가 시작됩니다.</li>'}${plan.stopIds.map((id,index)=>pointRow(id,index,'spot')).join('')}${pointRow(plan.finishId,-1,'finish')}</ol>
      ${stats.issues.filter(issue=>issue.placeId).map(issue=>`<p class="rp-error">${esc(issue.message)}</p>`).join('')}
      ${ready?stats.issues.filter(issue=>issue.code==='UNREACHABLE').map(issue=>`<p class="rp-error">${esc(issue.message)}</p>`).join(''):''}
      <button class="rp-browse-button" type="button" data-rp-action="find">${plan.startId?'+ 지도에서 경유지 고르기':'지도에서 출발지 고르기'}</button></div>
      <section class="rp-next"><div class="rp-section-title"><h3>다음 경유 후보</h3><span>${plan.startId?`${esc(byId.get(currentId())?.name||'현재 지점')} 기준`:''}</span></div>${rec.length?rec.map(r=>card(byId.get(r.placeId),{recommendation:r})).join(''):ready&&plan.startId?'<p class="rp-caption">연결 가능한 다음 후보가 없습니다. 다른 장소를 선택해 보세요.</p>':'<p class="rp-caption">출발지를 고르면 진행 방향에 맞는 후보를 보여드립니다.</p>'}</section></div>`;}
    function placesContent(){const starting=!plan.startId,items=filterItems.filter(p=>p.kind===(starting?'start':'spot')),chosen=selected&&byId.get(selected.id)?.kind===(starting?'start':'spot')?byId.get(selected.id):null;return `${replaceId?`<div class="rp-replacing"><strong>${esc(byId.get(replaceId)?.name)} 교체 중</strong><button type="button" data-rp-action="cancel-replace">취소</button></div>`:''}${chosen?`<section class="rp-selected-place"><div class="rp-section-title"><h3>선택한 장소</h3><button type="button" data-rp-action="detail" data-id="${esc(chosen.id)}">장소 정보</button></div>${card(chosen)}</section>`:''}<div class="rp-section-title"><h3>${starting?'출발지 고르기':'출발지에서 가까운 스팟'}</h3><span>${items.length}곳</span></div><p class="rp-caption">${starting?'먼저 동해안이나 부산의 출발지를 선택해 주세요.':'가까운 순서로 둘러보고 다음 경유지를 골라보세요.'}</p><div class="rp-place-results">${items.slice(0,candidateLimit).map(p=>card(p)).join('')||'<p class="rp-caption">조건에 맞는 장소가 없습니다.</p>'}</div>${items.length>candidateLimit?'<button type="button" class="rp-browse-button" data-rp-action="more">장소 더 보기</button>':''}`;}
    function savedContent(){if(!account.linked)return '<div class="rp-empty"><h3>다음에도 이어서 준비하세요</h3><p>로그인하면 참가 신청 없이도 루트를 저장하고 다시 불러올 수 있어요.</p><button type="button" class="rp-primary" data-rp-action="login">로그인</button></div>';let items;try{items=store.list(account);}catch(error){return `<p class="rp-error">${esc(error.message)}</p>`;}return `<div class="rp-section-title"><h3>내 루트</h3><button type="button" data-rp-action="new">새 루트</button></div>${items.length?items.map(item=>{const stats=status(item);return `<article class="rp-saved"><span>${stats.complete?'완성':'초안'} · 경유 ${item.stopIds.length}곳</span><h3>${esc(item.title)}</h3><p>${esc(byId.get(item.startId)?.name||'출발지 미정')} → ${esc(byId.get(item.finishId)?.name)}</p><small>${km(stats.distanceMeters)} · ${time(stats.durationSeconds)}</small><div><button type="button" data-rp-action="load" data-id="${esc(item.id)}">불러오기</button><button type="button" data-rp-action="duplicate" data-id="${esc(item.id)}">복제해 편집</button><button type="button" data-rp-action="delete" data-id="${esc(item.id)}">삭제</button></div></article>`;}).join(''):'<div class="rp-empty"><h3>저장한 루트가 없어요</h3><p>경유지를 모두 고르기 전에도 초안으로 저장할 수 있어요.</p><button type="button" class="rp-primary" data-rp-action="route-tab">루트 만들기</button></div>'}`;}
    function previewContent(){const p=preview.plan,stats=status(p);return `<section class="rp-preview"><span class="rp-preview-tag">${preview.type==='optimize'?'방문 순서 제안':'추천 루트 미리보기'}</span><h3>${p.stopIds.length}곳을 잇는 하루</h3><div class="rp-preview-metrics">${distanceSummary(p)}</div>${preview.type==='optimize'?`<p>기존 ${km(status().distanceMeters)} → 변경 ${km(stats.distanceMeters)}</p>`:'<p>직접 선택한 스팟은 그대로 포함했습니다.</p>'}${p.stopIds.length<10?`<p class="rp-error">연결 가능한 후보를 ${p.stopIds.length}곳 찾았습니다. 적용 후 경유지를 더 골라주세요.</p>`:''}<ol>${p.stopIds.map(id=>`<li>${esc(byId.get(id)?.name||id)}</li>`).join('')}</ol><div class="rp-preview-actions"><button type="button" class="rp-primary" data-rp-action="apply-preview">이 루트 적용</button>${preview.type==='auto'?'<button type="button" data-rp-action="another">다른 조합</button>':''}<button type="button" data-rp-action="cancel-preview">취소</button></div></section>`;}
    function render(){if(disposed)return;const scrollTop=host.querySelector('.rp-scroll')?.scrollTop||0,stats=status(),currentFocus=host.contains(document.activeElement)?document.activeElement?.id:null;
      host.className='route-planner';host.dataset.sheet=sheet;host.hidden=!active;
      host.innerHTML=`<div class="rp-header"><button type="button" class="rp-sheet-toggle" data-rp-action="sheet" aria-label="루트 패널 높이 변경"><span></span></button><div class="rp-title-row"><div><p>MY ROUTE</p><h2>나의 주행 루트</h2></div><button type="button" class="rp-fit" data-rp-action="fit">전체 경로</button></div><div class="rp-summary"><span class="${stats.spotCount>=10?'is-complete':''}">경유 <strong>${stats.spotCount}</strong> / 10곳</span><div>${distanceSummary()}</div></div><div class="rp-sheet-steps" role="group" aria-label="패널 높이">${[['summary','요약'],['half','중간'],['full','전체']].map(([key,label])=>`<button type="button" data-rp-action="sheet-size" data-size="${key}" aria-pressed="${key===sheet}">${label}</button>`).join('')}</div></div>
      <div class="rp-tabs" role="tablist" aria-label="루트 편집 메뉴">${[['route','내 경로'],['places','장소 찾기'],['saved','내 루트']].map(([key,label])=>`<button type="button" id="rp-tab-${key}" role="tab" data-rp-action="tab" data-tab="${key}" aria-selected="${tab===key}" aria-controls="rp-panel">${label}</button>`).join('')}</div>
      <div class="rp-scroll" id="rp-panel" role="tabpanel" aria-labelledby="rp-tab-${tab}">${preview?previewContent():tab==='route'?routeContent():tab==='places'?placesContent():savedContent()}</div>
      <footer class="rp-footer"><div class="rp-operation" role="status">${providerError?`<span class="rp-error">${esc(providerError)}</span> <button type="button" data-rp-action="retry-provider">다시 시도</button>`:!ready?'도로 데이터를 준비하고 있습니다. 장소 선택은 계속할 수 있어요.':routeBusy?'선택한 장소 사이의 도로를 연결하고 있습니다.':routeError?`<span class="rp-error">${esc(routeError)}</span> <button type="button" data-rp-action="retry-route">다시 계산</button>`:'예상 시간은 주행 기준이며 정차·실시간 교통은 포함하지 않습니다.'}</div><label class="rp-name"><span class="spot-sr">루트 이름</span><input id="rp-title" type="text" maxlength="60" placeholder="루트 이름" value="${esc(plan.title)}" autocomplete="off"></label><div class="rp-save-row"><span>${dirty?'저장하지 않은 변경사항':plan.id?'저장한 루트':'자유롭게 편집해 보세요'}</span><button type="button" class="rp-primary" data-rp-action="save">${!account.linked?'로그인하고 저장':stats.complete?'루트 저장':'초안 저장'}</button></div></footer><p class="rp-notice" role="status" hidden></p>`;
      host.querySelector('.rp-scroll').scrollTop=scrollTop;
      if(currentFocus)host.querySelector('#'+CSS.escape(currentFocus))?.focus({preventScroll:true});
    }
    function closeDialog(){disposeDialog?.();disposeDialog=null;dialog?.close();dialog?.remove();dialog=null;}
    function openDialog(title,html){closeDialog();dialog=document.createElement('dialog');dialog.className='rp-dialog';dialog.innerHTML=`<div class="rp-dialog-head"><h2>${esc(title)}</h2><button type="button" data-close aria-label="닫기">×</button></div><div class="rp-dialog-body">${html}</div>`;document.body.append(dialog);dialog.querySelector('[data-close]').addEventListener('click',closeDialog);dialog.addEventListener('cancel',()=>setTimeout(closeDialog));dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog();});dialog.showModal();return dialog;}
    function confirmAction(title,message,action){const modal=openDialog(title,`<p>${esc(message)}</p><div class="rp-dialog-actions"><button type="button" data-cancel>취소</button><button type="button" class="rp-primary" data-confirm>확인</button></div>`);modal.querySelector('[data-cancel]').onclick=closeDialog;modal.querySelector('[data-confirm]').onclick=()=>{closeDialog();action();};}
    async function login(saveAfter=false){persist();const modal=openDialog('루트 저장을 위한 로그인','<div class="rp-auth"></div>');disposeDialog=root.SSKR_SOCIAL_AUTH.mount(modal.querySelector('.rp-auth'),{title:'나의 루트를 저장하세요',note:'참가 신청 없이도 이용할 수 있습니다.',onSelect:async loginProvider=>{account=await options.onLogin(loginProvider);persist();closeDialog();render();if(saveAfter)save();}});}
    function save(){if(!account.linked){login(true);return;}try{plan=store.save({...plan,routingVersion:ready?provider.version:plan.routingVersion},account);dirty=false;persist();render();notify(status().complete?'루트를 저장했습니다.':'초안을 저장했습니다. 다음에 이어서 편집할 수 있어요.');}catch(error){notify(error?.message||'저장하지 못했습니다. 다시 시도해 주세요.',true);}}
    async function showPreview(type){if(!ready||!plan.startId)return;const next=type==='auto'?domain.autoFill(plan,catalog,provider,{variant:variant++}):domain.optimize(plan,provider);const token=++routeRequest;routeAbort?.abort();routeAbort=new AbortController();routeBusy=false;preview={type,plan:next,result:null};tab='route';render();mapPlan(next);
      try{const previewResult=await provider.route(domain.orderedIds(next),{signal:routeAbort.signal});if(disposed||token!==routeRequest||!preview)return;preview.result=previewResult;syncMap();}catch(error){if(error?.name!=='AbortError'&&token===routeRequest)notify('미리보기 도로를 불러오지 못했습니다. 다시 시도해 주세요.',true);}}
    function editSaved(id,duplicate=false){let saved;try{saved=store.get(id,account);}catch(error){notify(error.message,true);return;}if(!saved)return;const action=()=>{if(duplicate)saved={...saved,id:null,title:`${saved.title.slice(0,57)} 복사`,createdAt:null,updatedAt:null};undo.length=0;plan=domain.normalize(saved,catalog);dirty=duplicate;anchorId=plan.stopIds.at(-1)||plan.startId;selected=byId.get(anchorId)||null;preview=null;tab='route';options.onStartChange?.(plan.startId);persist();calculate();if(anchorId)viewer.select?.(anchorId);};dirty?confirmAction('루트를 불러올까요?','저장하지 않은 현재 변경사항은 바뀝니다.',action):action();}
    function newPlan(){const action=()=>{undo.length=0;plan=domain.createEmpty(catalog);dirty=false;anchorId=null;preview=null;selected=null;tab='route';options.onStartChange?.(null);persist();calculate();};dirty?confirmAction('새 루트를 만들까요?','저장하지 않은 현재 변경사항은 바뀝니다.',action):action();}
    function showDetail(id){const p=byId.get(id);if(!p)return;const modal=openDialog(p.name,`${p.image?`<img class="rp-detail-image" src="${esc(p.image)}" alt="${esc(p.name)}" referrerpolicy="no-referrer">`:''}<p class="rp-detail-region">${esc(p.region)} · ${esc(p.kind==='spot'?categories[p.category]||'스팟':p.kind==='start'?'출발지':'고정 도착지')}</p><p>${esc(p.description||p.lead)}</p><p>${esc(p.address||'')}</p><p class="rp-caption">${esc(p.note)}</p><button type="button" class="rp-primary" data-detail-add ${p.kind==='finish'||plan.stopIds.includes(id)?'disabled':''}>${p.kind==='start'?'출발지 선택':plan.stopIds.includes(id)?'선택됨':'+ 경유지 추가'}</button>`);modal.querySelector('[data-detail-add]').onclick=()=>{closeDialog();add(id);};}
    host.addEventListener('click',event=>{const button=event.target.closest('[data-rp-action]');if(!button||button.disabled)return;const action=button.dataset.rpAction,id=button.dataset.id;
      if(action==='sheet'||action==='sheet-size'){sheet=action==='sheet-size'?button.dataset.size:sheet==='summary'?'half':sheet==='half'?'full':'summary';host.dataset.sheet=sheet;render();return;}
      if(action==='tab'){tab=button.dataset.tab;if(sheet==='summary')sheet='half';render();return;}
      if(action==='select'){select(byId.get(id));viewer.select?.(id);return;}
      if(action==='anchor'){anchorId=id===plan.finishId?plan.stopIds.at(-1)||plan.startId:id;selected=byId.get(anchorId);viewer.select?.(anchorId);render();syncMap();persist();return;}
      if(action==='add'){add(id);return;}
      if(action==='remove'){if(anchorId===id)anchorId=plan.startId;if(selected?.id===id){selected=byId.get(anchorId)||null;if(anchorId)viewer.select?.(anchorId);}change({...plan,stopIds:plan.stopIds.filter(stop=>stop!==id)},'경유지를 삭제했습니다.');return;}
      if(action==='up'||action==='down'){const stops=plan.stopIds.slice(),index=stops.indexOf(id),target=index+(action==='up'?-1:1);if(index>=0&&target>=0&&target<stops.length){[stops[index],stops[target]]=[stops[target],stops[index]];change({...plan,stopIds:stops});}return;}
      if(action==='replace'){replaceId=id;tab='places';options.onFindPlaces?.();render();return;}
      if(action==='cancel-replace'){replaceId=null;render();return;}
      if(action==='undo'&&undo.length){plan=undo.pop();dirty=true;preview=null;anchorId=plan.stopIds.at(-1)||plan.startId;selected=byId.get(anchorId)||null;options.onStartChange?.(plan.startId);persist();calculate();if(anchorId)viewer.select?.(anchorId);return;}
      if(action==='find'){tab='places';options.onFindPlaces?.();render();return;}
      if(action==='route-tab'){tab='route';render();return;}
      if(action==='more'){candidateLimit+=12;render();return;}
      if(action==='fit'){viewer.fitRoute?.();return;}
      if(action==='autofill'||action==='another'){showPreview('auto');return;}
      if(action==='optimize'){showPreview('optimize');return;}
      if(action==='apply-preview'&&preview){const next=preview.plan;change(next,'추천 루트를 적용했습니다.');return;}
      if(action==='cancel-preview'){preview=null;calculate();return;}
      if(action==='retry-route'){calculate();return;}
      if(action==='retry-provider'){loadProvider();return;}
      if(action==='save'){save();return;}
      if(action==='login'){login();return;}
      if(action==='new'){newPlan();return;}
      if(action==='load'||action==='duplicate'){editSaved(id,action==='duplicate');return;}
      if(action==='delete'){confirmAction('저장한 루트를 삭제할까요?','삭제한 루트는 복구할 수 없습니다.',()=>{try{store.remove(id,account);if(plan.id===id){plan={...plan,id:null,createdAt:null,updatedAt:null};dirty=true;persist();}render();notify('저장한 루트를 삭제했습니다.');}catch(error){notify(error.message,true);}});return;}
      if(action==='detail')showDetail(id);
    },{signal:events.signal});
    host.addEventListener('change',event=>{if(event.target.id==='rp-start')event.target.value?start(event.target.value):(anchorId=null,selected=null,change({...plan,startId:null}),options.onStartChange?.(null));},{signal:events.signal});
    host.addEventListener('input',event=>{if(event.target.id==='rp-title'){plan.title=event.target.value;dirty=true;persist();host.querySelector('.rp-save-row>span').textContent='저장하지 않은 변경사항';}},{signal:events.signal});
    let draggedId=null;host.addEventListener('dragstart',event=>{const row=event.target.closest('[data-waypoint][draggable]');if(!row)return;draggedId=row.dataset.waypoint;event.dataTransfer.setData('text/plain',draggedId);event.dataTransfer.effectAllowed='move';row.classList.add('is-dragging');},{signal:events.signal});
    host.addEventListener('dragover',event=>{if(draggedId&&event.target.closest('[data-waypoint][draggable]')){event.preventDefault();event.dataTransfer.dropEffect='move';}},{signal:events.signal});
    host.addEventListener('drop',event=>{const target=event.target.closest('[data-waypoint][draggable]')?.dataset.waypoint;if(!draggedId||!target||target===draggedId)return;event.preventDefault();const stops=plan.stopIds.slice(),from=stops.indexOf(draggedId),to=stops.indexOf(target);if(from>=0&&to>=0){stops.splice(from,1);stops.splice(to,0,draggedId);change({...plan,stopIds:stops});}draggedId=null;},{signal:events.signal});
    host.addEventListener('dragend',()=>{draggedId=null;host.querySelector('.is-dragging')?.classList.remove('is-dragging');},{signal:events.signal});
    async function loadProvider(){providerStarted=true;providerError='';render();try{await provider.ready();if(disposed)return;ready=true;options.onRoadReady?.();calculate();}catch(error){if(disposed)return;providerError=roadMessage(error);render();}}
    const map=viewer.getMap?.();map?.on('moveend',persist);root.addEventListener('pagehide',persist,{signal:events.signal});
    if(scrollRestore&&active&&map){map.setView([scrollRestore.lat,scrollRestore.lng],scrollRestore.zoom,{animate:false});requestAnimationFrame(()=>{if(!disposed)root.scrollTo({top:scrollRestore.scrollY||0,behavior:'instant'});});}
    setMode(active);
    return {isActive:()=>active,hasStart:()=>Boolean(plan.startId),distanceFromStart:id=>ready&&plan.startId?provider.summary(plan.startId,id)?.distanceMeters:null,startPlace:()=>byId.get(plan.startId),setMode,select,openPlace(place){if(!active||!place||!plan.startId&&place.kind!=='start')return;select(place);showDetail(place.id);},setFilters(items){filterItems=items;candidateLimit=12;if(active&&tab==='places')render();},destroy(){persist();disposed=true;events.abort();routeAbort?.abort();map?.off('moveend',persist);clearTimeout(flashTimer);closeDialog();viewer.setEditing?.(false);}};
  }
  root.SSKR_ROUTE_PLANNER={mount};
})(typeof globalThis!=='undefined'?globalThis:this);
